services:
  # Banco de Dados PostgreSQL
  db-fitness:
    image: postgres:17
    container_name: postgres-fitness
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fitness_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Mensageria RabbitMQ
  rabbitmq-fitness:
    image: rabbitmq:3-management
    container_name: rabbitmq-fitness
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest